import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

logger = logging.getLogger(__name__)

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_NAME = os.getenv("FROM_NAME", "Rabbitt AI — Sales Insights")


def send_email(recipient: str, summary: str, filename: str) -> None:
    """Send the AI-generated summary to the recipient via SMTP."""
    if not SMTP_USER or not SMTP_PASSWORD:
        logger.warning("SMTP credentials not configured — skipping email send")
        logger.info(f"[MOCK EMAIL] To: {recipient}\n\n{summary}")
        return

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"📊 Sales Insight Brief — {datetime.now().strftime('%B %d, %Y')}"
        msg["From"] = f"{FROM_NAME} <{SMTP_USER}>"
        msg["To"] = recipient

        # Plain text fallback
        plain_text = f"Sales Insight Brief\n{'='*40}\n\n{summary}\n\nGenerated from: {filename}\nPowered by Rabbitt AI"

        # HTML version
        html_body = _build_html(summary, filename)

        msg.attach(MIMEText(plain_text, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, recipient, msg.as_string())

        logger.info(f"Email successfully sent to {recipient}")

    except Exception as e:
        logger.error(f"Failed to send email to {recipient}: {e}")
        raise


def _build_html(summary: str, filename: str) -> str:
    # Convert markdown-ish summary to basic HTML
    lines = summary.split("\n")
    html_lines = []
    for line in lines:
        if line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("**") and line.endswith("**"):
            html_lines.append(f"<p><strong>{line[2:-2]}</strong></p>")
        elif line.startswith("- "):
            html_lines.append(f"<li>{line[2:]}</li>")
        elif line.strip() == "":
            html_lines.append("<br>")
        else:
            html_lines.append(f"<p>{line}</p>")

    content = "\n".join(html_lines)
    date_str = datetime.now().strftime("%B %d, %Y")

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }}
  .container {{ max-width: 640px; margin: 40px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }}
  .header {{ background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); padding: 32px; color: #fff; }}
  .header h1 {{ margin: 0; font-size: 22px; font-weight: 700; letter-spacing: -0.3px; }}
  .header p {{ margin: 6px 0 0; opacity: 0.7; font-size: 13px; }}
  .body {{ padding: 32px; color: #1a202c; line-height: 1.7; }}
  h2 {{ color: #0f172a; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
  h3 {{ color: #2d3748; font-size: 15px; margin-top: 20px; }}
  li {{ margin: 6px 0; color: #4a5568; }}
  .footer {{ background: #f8fafc; padding: 20px 32px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #a0aec0; }}
  .badge {{ display: inline-block; background: #ebf8ff; color: #2b6cb0; padding: 2px 10px; border-radius: 99px; font-size: 12px; font-weight: 600; margin-top: 8px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📊 Sales Insight Brief</h1>
    <p>{date_str} &nbsp;·&nbsp; Source: {filename}</p>
  </div>
  <div class="body">
    {content}
  </div>
  <div class="footer">
    Generated by <strong>Rabbitt AI — Sales Insight Automator</strong><br>
    <span class="badge">Powered by Gemini AI</span>
  </div>
</div>
</body>
</html>"""
